# Generated by Django 2.1.8 on 2019-04-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Facebook')),
            ],
        ),
    ]
